CREATE SCHEMA IF NOT EXISTS coffee_machine;

CREATE TABLE IF NOT EXISTS coffee_machine.coffee(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) UNIQUE NOT NULL,
    milk integer NOT NULL,
    boiled_water integer NOT NULL,
    coffee_beans integer NOT NULL,
    price float NOT NULL
);

CREATE TABLE IF NOT EXISTS coffee_machine.storage(
    id uuid DEFAULT gen_random_uuid (),
    milk integer CHECK (milk>=0) NOT NULL,
    boiled_water integer CHECK (boiled_water>=0) NOT NULL,
    coffee_beans integer CHECK (coffee_beans>=0) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS coffee_machine.purchase_history(
    id uuid DEFAULT gen_random_uuid (),
    coffee_id integer NOT NULL,
    operation_date date NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (coffee_id) REFERENCES coffee_machine.coffee(id)
);