instance:
  name: demo_aisa

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aisa_coffeeMachine
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
